<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>404错误提示</title>
        <style type="text/css">
            body {font-size:14px;color:#3f3f3f;margin:0;padding:0;text-align:left;font-family:Arial;background-color:#fff}
            form, img, ul, li, p, dl, dt, dd, span, p {border:0;margin:0;padding:0;}
            h1, h2, h3, h4 {font-size:12px;font-weight:100;margin:0;padding:0;}
            li, dl {list-style-type:none;}
            .clear {clear:both;}
            .box {width:960px;margin:80px auto 0 auto;}
            .title {height:30px;background-color:#efeeef;border:#efeeef 1px solid;padding:1px;line-height:32px;font-weight:bold;padding-left:15px;}
            .neirong {border:#ccc 1px solid;margin-top:16px; padding-top:14px;}
            .neirongb{border-bottom:#CCC 1px dotted; padding-bottom:20px;}
            .neirongb dl{ float:left; }
            .neirongb dd {float:left; padding-left:108px; padding-top:5px;}
            .neirongb dt {float:left; padding-left:85px; width:602px;}
            .weizibiaoti{ border-bottom:#CCC 1px dotted; line-height:32px; font-weight:bold;}
            .wenzinerong{ line-height:24px; padding-top:8px;}
            .doahanglanmu{ padding-top:8px;}
            .doahanglanmu li{ line-height:25px; font-weight:bold;}
            .doahanglanmu a{ color:#e07604;}
            .doahanglanmu a:hover{ text-decoration:underline; color:#C00}
            .fanhuannaiu{ padding:12px 0; text-align:center;}
            .fanhuannaiu img{ margin-right:18px;}
            .dibudaohang{ text-align:center; line-height:30px; font-size:12px; color:#666}
            .dibudaohang a{ color:#666; padding:0 10px; text-decoration:none}
            .dibudaohang a:hover{ color:#333; text-decoration:underline;}
        </style>
    </head>
    <body>
        <div class="box">
            <div class="title">网站首页</div>
            <div class="neirong">
                <div class="neirongb">
                    <dl>
                        <dd><img src="__PUBLIC__/home/images/404.jpg" width="113" height="112" /></dd>
                        <dt>
                            <div class="weizibiaoti">[网站404页面缺失提示信息]</div>
                            <div class="wenzinerong">很抱歉，您要访问的页面已经不存在或者已经被管理员移到其他的栏目，
                                同时请仔细检查一下浏览器地址栏，您要访问的地址是否正确。
                                <br />
                                一下是我们的快速网站频道导航： </div>
                        </dt>
                    </dl>
                    <div class="clear"></div>
                    <div>
                    </div>
                </div>
                <div class="fanhuannaiu">
                    <a href="__APP__"><img src="__PUBLIC__/home/images/404_03.jpg" width="68" height="26" /></a>
                    <a href="javascript:history.back()();"><img src="__PUBLIC__/home/images/404_05.jpg" width="68" height="26" /></a></div>
                <div class="clear"></div>
            </div>
        </div>
    </body>
</html>
