<title>红亚科技</title>
<link href="__PUBLIC__/home/css/master.css" rel="stylesheet" type="text/css" />
<script src="__PUBLIC__/home/js/jquery1.42.min.js" type="text/javascript"></script>
<script src="__PUBLIC__/home/js/jquery.SuperSlide.2.1.1.js" type="text/javascript"></script>
<script src="__PUBLIC__/home/js/hy_main.js" type="text/javascript"></script>
<!--[if IE 6]>
<script src="__PUBLIC__/home/js/iepng.js" type="text/javascript"></script>
<script type="text/javascript">
   EvPNG.fix('div, ul, img, li, input'); 
</script>
<![endif]-->