<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php require_once APP_PATH . "/Tpl/header.phtml"; ?>
    </head>
    <body style=" background:url(__PUBLIC__/home/images/yansedjiogeg.png) 0 0 repeat;">
        <div class="yonghuxingxi">
            <!--<div class="yhguanbi"><a href="#"><img src="__PUBLIC__/home/images/cha.png" width="16" height="16" /></a></div>-->
            <div class="yhxxwemzi">
                <div>
                    <p class="yhxxwemzia">用户名：</p>
                    <p class="yhxxwemzib"><?php echo $user['user_name']; ?></p>
                    <div class="clear"></div>
                </div>

                <div>
                    <p class="yhxxwemzia">学校：</p>
                    <p class="yhxxwemzib"><?php echo $user['campus_name']; ?></p>
                    <div class="clear"></div>
                </div>
                <div>
                    <p class="yhxxwemzia">学院：</p>
                    <p class="yhxxwemzib"><?php echo $user['academy_name']; ?></p>
                    <div class="clear"></div>
                </div>
                <div>
                    <p class="yhxxwemzia">专业：</p>
                    <p class="yhxxwemzib"><?php echo $user['major_name']; ?></p>
                    <div class="clear"></div>
                </div>
                <div>
                    <p class="yhxxwemzia">年级：</p>
                    <p class="yhxxwemzib"><?php echo $user['grade_name']; ?></p>
                    <div class="clear"></div>
                </div>
                <div>
                    <p class="yhxxwemzia">班级：</p>
                    <p class="yhxxwemzib"><?php echo $user['class_name']; ?></p>
                    <div class="clear"></div>
                </div>
                <div>
                    <p class="yhxxwemzia">所属战队：</p>
                    <p class="yhxxwemzib"><?php echo $user['team_name']; ?></p>
                    <div class="clear"></div>
                </div>
                <div class="tijiaxinganniu">
                    <a href="__APP__/user/edit">修改</a>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </body>
</html>
