<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php require_once APP_PATH . "/Tpl/header.phtml"; ?>
    </head>
    <body>
        <div class="box">
            <div class="top">
                <div class="logo">
                    <p class="logoa"><img src="__PUBLIC__/home/images/logo.png" width="142" height="50" /></p>
                    <p class="logob"><?php echo session('title'); ?>    </p>
                </div>
                <div class="clear"></div>
            </div>
            <div class="yonghudengluimg">
                <form name="login_form" method="POST" action="__APP__/Login/login">
                    <div class="dengliuzweiimg">
                        <div class="denglwuiekuang">
                            <p class="zhneghudengiemg">登录账号</p>
                            <div class="xiadanewedweg_dl" style=" margin-top:51px;">
                                <p class="dengluwemzia_b">用户名：</p>
                                <input name="username" type="text" class="dengluinwgdengl" />
                                <div class="clear"></div>
                            </div>
                            <div class="xiadanewedweg_dl">
                                <p class="dengluwemzia_b">密&nbsp;&nbsp;&nbsp;&nbsp;码：</p>
                                <input name="password" type="password" class="dengluinwgdengl" />
                                <div class="clear"></div>
                            </div>
                            <div class="wangjiwemgfiwfux">
                                <?php if ($err) : ?>
                                    <p class="zidongdelgu" style="color:red;">用户名或者密码错误!，请重新登录</p>
                                <?php endif; ?>
                                <div class="clear"></div>
                            </div>
                            <div class="dengiigmg"> 
                                <p class="dengiigmga">
                                    <a href="javascript:login_form.submit();">登录</a>
                                </p>
                                <?php if ($is_register == 1): ?>
                                    <p class="lijizhuanniu">
                                        <a href="__APP__/login/regeist">立即注册＞＞</a>
                                    </p>
                                    <div class="clear"></div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </body>
    <script>
        $(function () {
            $("body").keydown(function () {
                if (window.event.keyCode==13) 
                {login_form.submit();}
                
            });
        });
    </script>
</html>
