<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php require_once APP_PATH . "/Tpl/header.phtml"; ?>
    </head>
    <body style=" background:url(__PUBLIC__/home/images/yansedjiogeg.png) 0 0 repeat;">
        <div class="yonghuxingxi">
            <div class="yhguanbi"><a href="#"><img src="__PUBLIC__/home/images/cha.png" width="16" height="16" /></a></div>
            <div class="yhxxwemzi">
                <form name="form" method="post" action="__APP__/login/rege">
                    <div class="xiadanewedweg">
                        <p class="yhxxwemzia_b">用户名：</p>
                        <input name="name" type="text" class="yonghuminwgdengl" />
                        <div class="clear"></div>
                    </div>
                    <div class="xiadanewedweg">
                        <p class="yhxxwemzia_b">学校：</p>
                        <select name="campus" id="campus" class="xialailewge">
                            <option value="">=选择学校=</option>
                            <?php foreach ($campus_array as $campus): ?>
                                <option value="<?php echo $campus['campus_id']; ?>"><?php echo $campus['campus_name']; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <div class="clear"></div>
                    </div>
                    <div class="xiadanewedweg">
                        <p class="yhxxwemzia_b">学院：</p>
                        <select name="academy" id="academy" class="xialailewge">
                            <option value=''>=选择学院=</option>
                        </select>
                        <div class="clear"></div>
                    </div>
                    <div class="xiadanewedweg">
                        <p class="yhxxwemzia_b">专业：</p>
                        <select name="major" id="major" class="xialailewge">
                            <option value=''>=选择专业=</option>
                        </select>
                        <div class="clear"></div>
                    </div>
                    <div class="xiadanewedweg">
                        <p class="yhxxwemzia_b">年级：</p>
                        <select name="grade" class="xialailewge">
                            <?php foreach ($grade_array as $grade): ?>
                                <option value="<?php echo $grade['grade_id']; ?>"><?php echo $grade['grade_name']; ?></option>
                            <?php endforeach; ?>
                        </select>
                        <div class="clear"></div>
                    </div>
                    <div class="xiadanewedweg">
                        <p class="yhxxwemzia_b">班级：</p>
                        <select name="class" id="class" class="xialailewge">
                            <option value=''>=选择班级=</option>
                        </select>
                        <div class="clear"></div>
                    </div>
                    <div class="xiadanewedweg">
                        <p class="yhxxwemzia_b">密码：</p>
                        <input name="pwd" type="password" class="yonghuminwgdengl" />
                        <div class="clear"></div>
                    </div>
                    <div class="xiadanewedweg">
                        <p class="yhxxwemzia_b">确认密码：</p>
                        <input name="cpwd" type="password" class="yonghuminwgdengl" />
                        <div class="clear"></div>
                    </div>
                    <div class="tijiaxinganniu">
                        <a href="javascript:form.submit()">提交</a>
                    </div>
                    <div class="clear"></div>
                </form>
            </div>
        </div>
    </body>
    <script>
        $('#campus').change(function () {
            $.get("__APP__/login/get", {campus: $(this).val()}, function (res) {
                var data = "<option value=''>=选择学院=</option>" + res.data;
                $('#academy').html(data);
            }, 'json');
        });
        $('#academy').change(function () {
            $.get("__APP__/login/get", {academy: $(this).val()}, function (res) {
                var data = "<option value=''>=选择专业=</option>" + res.data;
                $('#major').html(data);
            }, 'json');
        });
        $('#major').change(function () {
            $.get("__APP__/login/get", {major: $(this).val()}, function (res) {
                var data = "<option value=''>=选择班级=</option>" + res.data;
                $('#class').html(data);
            }, 'json');
        });
    </script>
</html>
