<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php require_once APP_PATH . "/Tpl/header.phtml"; ?>
    </head>
    <body>
        <div class="box">
            <?php require_once APP_PATH . "/Tpl/top.phtml"; ?>
            <div class="jingsaipeiming">
                <div class="jingsaipeiminga">
                    <a href='<?php echo U('resist/index'); ?>'>红蓝对抗</a>><?php echo $resist['competition_name']; ?>
                </div>
                <div class="jingsaipeimingb">
                    <ul>
                        <li><a href="<?php echo U('resist/info', array('id' => $resist['competition_id'])); ?>">大赛公告</a></li>
                        <li><a href="<?php echo U('resist/score', array('tid' => $resist['competition_id'])); ?>">查看排名</a></li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
            <div class="landuirulkop" style=" padding-bottom:50px;">
                <div class="landuirulkopa">
                    <form id="ip">
                        <p style=" float:left; line-height:66px;">提交本队目标访问地址：</p>
                        <p class="landuirulkopab">
                            <input name="ip" type="text" value="" class="landuirulkopabwb" />
                            <input name="resist" type="hidden" value="<?php echo $resist['competition_id']; ?>" class="landuirulkopabwb" />
                        </p>
                        <p class="tijiawanigahnegg"><a href="javascript:sub()">提交</a></p>
                    </form>
                </div>
                <div class="tabqiehuan">
                    <div class="tabqiehuana">
                        <ul>
                            <?php $i = 0; ?>
                            <?php foreach ($vms_array as $vms) : ?>
                                <?php $i ++; ?>
                                <li >
                                    <a href="#" title="<?php echo $vms['name'] ?>"><?php echo $i; ?></a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                        <div class="clear"></div>
                    </div>
                    <div class="tabqiehuanb">
                        <?php foreach ($vms_array as $vms) : ?>
                            <div class="tabqiehuanbaefe">
                                <div class="wuduqidienwgeg">
                                    <iframe src="<?php echo U('resist/start', array('id' => $vms['name'])); ?>" width="513" height="447"></iframe>
                                </div>
                                <div class="quanpeinganiu">
                                    <ul>
                                        <li><a href="<?php echo U('resist/start', array('id' => $vms['name'])); ?>">启动本组靶机</a></li>
                                        <li><a target="_blank" href="<?php echo $vms['url']; ?>">全屏</a></li>
                                    </ul>
                                    <div class="clear"></div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>

                <div class="tabqiehuan_right" >
                    <div class="xuliebhaweig">
                        <p class="xuliebhaweigpa">序列</p>
                        <p class="xuliebhaweigpb">题目</p>
                        <p class="xuliebhaweigpa">分值</p>
                        <p class="xuliebhaweigpa">状态</p>
                        <div class="clear"></div>
                    </div>
                    <?php $i = ($p - 1)*6; ?>
                    <?php foreach ($question_array as $question): ?>
                        <?php $i++; ?>
                        <div class="xuliebhaweig">
                            <p class="xuliebhaweigpa"><?php echo $i; ?></p>
                            <p class="xuliebhaweigpb"><?php echo $question['gatename']; ?></p>
                            <p class="xuliebhaweigpa"><?php echo $question['score']; ?></p>
                            <?php if ($question['attack'] == 0): ?>
                                <p class="lvsebeijing">安全</p>
                            <?php else: ?>
                                <p class="hongsebeijing">沦陷</p>
                            <?php endif; ?>

                            <div class="clear"></div>
                        </div>
                    <?php endforeach; ?>
                    <div class="page">
                        <?php echo $page; ?>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <script type="text/javascript">
            $(".tabqiehuan").slide({targetCell: ".tabqiehuanbaefe", titCell: ".tabqiehuana ul li", autoPlay: false, titOnClassName: "ahover"});
            function sub() {
                $.ajax({
                    type: 'POST',
                    url: '__APP__/resist/ip/',
                    data: $('#ip').serialize(),
                    dataType: 'json',
                    success: function (msg) {
                        if (msg.status == 1) {
                            alert('设置成功');
                        } else {
                            alert('设置失败');
                        }
                    }
                });
            }
        </script>
    </body>
</html>
