<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php require_once APP_PATH . "/Tpl/header.phtml"; ?>
    </head>
    <body>
        <div class="box">
            <?php require_once APP_PATH . "/Tpl/top.phtml"; ?>
            <div class="jingsaipeiming" style=" margin-top:0px;">
                <div class="jingsaipeiminga"><a href="<?php echo U('resist/index'); ?>" >红蓝对抗</a>><?php echo $resist['competition_name']; ?></div>
                <div class="clear"></div>
            </div>
            <div class="shitigongago">
                <p class="peimingbgabs_b">大赛简介</p>
                <div class="shitigongagoa" style="line-height: normal">
                    <?php echo htmlspecialchars_decode($resist['competition_note']); ?>
                </div>
            </div>
        </div>
    </body>
</html>
