<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php require_once APP_PATH . "/Tpl/header.phtml"; ?>
    </head>
    <body>
        <div class="box">
            <?php require_once APP_PATH . "/Tpl/top.phtml"; ?>
            <div class="jingsaipeiming" style=" margin-top:0px;">
                <div class="jingsaipeiminga"><a href='<?php echo U('resist/index'); ?>'>红蓝对抗</a>><?php echo $target['competition_name'] ?></div>
                <div class="clear"></div>
            </div>
            <table class="peimingbg" style="width:990px;">
                <tr>
                    <td class="peimingbgab">
                        <p style=" height:74px;"></p>
                    </td>
                    <td class="peimingbga">
                        <p class="peimingbgabs">团队</p>
                    </td>
                    <td class="peimingbga">
                        <p class="peimingbgabs">成员</p>
                    </td>
                    <td class="peimingbga">
                        <p class="peimingbgabs">总分</p>
                    </td>
                </tr>
                <?php $i = 0; ?>
                <?php foreach ($score_array as $score): ?>
                    <?php $i++; ?>
                    <tr>
                        <td><?php echo $i; ?></td>
                        <td><?php echo $score['team_name']; ?></td>
                        <td><?php echo $score['team_members']; ?></td>
                        <td><?php echo $score['total_score']; ?></td>
                    </tr>
                <?php endforeach; ?>

<!--                <tr class="page">
                    <td colspan="5">
                        <span class="disabled"> &lt; </span>
                        <span class="current">1</span>
                        <a href="">2</a>
                        <a href="">3</a> 
                        <a href="">4</a> 
                        <a href="">5</a> 
                        <a href="">6</a> 
                        <a href="">7</a> 
                        <a href="">8</a> 
                        <a href="">......</a> 
                        <a href="">&gt;</a>
                    </td>
                </tr>-->
            </table>
        </div>
    </body>
    <script>
        $(function () {
            reloading();
        });
    </script>
</html>
